name:                co-house
version:             0.1.0.0
synopsis:            Haskell bindings to the UK Companies House's APIs.
category:            Web, Test
github:              "mpilgrem/co-house"
license:             BSD3
author:              "Mike Pilgrem"
maintainer:          "public@pilgrem.com"
copyright:           "Copyright 2021 Mike Pilgrem"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/mpilgrem/co-house#readme>

ghc-options:
- -Wall

flags:
  tools:
    description: Build developer tools
    default: false
    manual: false

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- directory
- filepath
- http-client
- http-client-tls
- http-media
- http-types
- modern-uri
- optparse-applicative
- servant
- servant-client
- servant-flatten
- text
- time
- yaml

library:
  source-dirs: src

executables:
  co-house:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - co-house
  tool-description:
    when:
      - condition: "!flag(tools)"
        buildable: false
    main:                Description.hs
    source-dirs:         tool
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - unordered-containers
